services:
  database:
    image: postgres:16.8-alpine
    container_name: database
    ports:
      - 5432:5432

    volumes:
      - app_db_volume:/var/lib/postgresql/data

    env_file:
      - .env

    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 5000:5000
    depends_on:
      - database

    env_file:
      - .env

    volumes:
      - .:/app

    links:
      - database

    restart: always

volumes:
  app_db_volume:

