version: '3.8'
services:
  database:
    image: postgres:16.8-alpine
    container_name: database
    ports:
      - 5432:5432

    volumes:
      - app_db_volume:/var/lib/postgresql/data

    env_file:
      - .env

    restart: always

volumes:
  app_db_volume:
